lane :test do
  ovo_import_full_repo_from_git(
    url: 'https://gitlab.com/your-org/your-repo.git',
    branch: "feature/refactor"
  )

  ovo_import_full_repo_from_git(
    url: 'https://gitlab.com/your-org/your-repo.git',
    version: ['>= 2.0.0', '< 3.0.0']
  )
end
